ARG IMAGE_VERSION="ubuntu:24.04"

FROM $IMAGE_VERSION

ARG IMAGE_VERSION

LABEL maintainer="DevDotNet.Org <anton@devdotnet.org>"
LABEL build_version="Image version:- ${IMAGE_VERSION}"

ENV LANG=C.UTF-8
ENV LANGUAGE=C.UTF-8

COPY copyables /

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
        openssh-server \
        mc \
        htop \
        iotop \
        ncdu \
        tar \
        zip \
        nano \
        vim \
        bash \
        sudo \
        sed \
        iputils-ping \
        traceroute \
        telnet \
        dnsutils \
        iperf \
        nmap \
    && rm -rf /etc/ssh/ssh_host_* \
    && mkdir -p /data \
    && rm -rf /var/lib/apt/lists/* \
    && chmod +x /entrypoint.sh

EXPOSE 22/tcp

ENTRYPOINT ["/entrypoint.sh"]

CMD ["/usr/sbin/sshd", "-D"]
